### ISSUE TITLE
Correção Exercício `0.5.1`

### ISSUE THREAD

**Issue by mathiasgheno** [TharsilaMS/Atividade.0.5.1#1]
# Correção Exercício `0.5.1`

> Considere o wireframe abaixo como um guia visual para um sistema web que faz listagem de tarefas considerando três status: Pendentes, Concluídas e Excluídas.  [Referência visual](https://i.imgur.com/AsfPVcN.jpg). 

O principal problema da sua entrega está na falta de otimização no uso do seu código. Note a quantidade de código duplicado de propriedades entre `Pendentes`, `Concluidos` e  `Excluidos`. 

https://github.com/TharsilaMS/Atividade.0.5.1/blob/e80b4b52e41e7901a2b7554144107d2b2f6017bc/TrabalhoDw/estilo.css#L34-L60

Você pode evitar isso fazendo uso de duas classes. Adicionando em uma classe as propriedades comuns e tratando as exceções (ou sobreescritas) em outra classe. Veja um exemplo abaixo. 

```css
.menu {
    display: inline;
    padding: 15px;
    border-radius: 10px;
    margin: 15px;
}

.excluida {
    border: 2px solid var(--cor-excluidas);
    background-color: var(--cor-excluidas);
}
```

```html
<a class="menu excluida" href="excluidas.html"> Excluidas </a>
```

**Nota:** 8.5

[^1]: [Caminhos: entenda as diferenças entre absolutos e relativos](https://www.alura.com.br/artigos/caminhos-entenda-diferencas-entre-absolutos-relativos?gclid=CjwKCAjw9J2iBhBPEiwAErwpeZOH615fG9QWBpSN2UuIKVbpf6WWD9sknST-4DwVDHzcCBBuMOYuzhoCbNsQAvD_BwE)
[^2]: [CSS Selectors ─ Element Element Selector](https://www.w3schools.com/cssref/sel_element_element.php)
[^3]: [CSS Variables ─ An Introduction](https://youtu.be/PHO6TBq_auI)
[^4]: [HTML Lists](https://www.w3schools.com/html/html_lists.asp)
